version: '3.7'
services:

    ping:
        build: ping

    calc:
        build: calc

    soma:
        build: soma

    sub:
        build: sub

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - ping
           - calc
           - soma
           - sub
